// <auto-generated />
namespace kredit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_statussurvey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_statussurvey));
        
        string IMigrationMetadata.Id
        {
            get { return "201802160235129_add_statussurvey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
