// <auto-generated />
namespace kredit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class autoincrement_idapprove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autoincrement_idapprove));
        
        string IMigrationMetadata.Id
        {
            get { return "201802150802121_autoincrement_idapprove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
